# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-22 12:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180521_1111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_opration', '0003_auto_20180521_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='\u5546\u54c1ID', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.Goods'),
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([]),
        ),
    ]
