# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-22 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_opration', '0004_auto_20180522_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsshop',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='goodsshop',
            name='user',
        ),
        migrations.DeleteModel(
            name='GoodsShop',
        ),
    ]
