# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-14 22:59
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='\u8f6e\u64ad\u56fe')),
                ('index', models.IntegerField(default=100, verbose_name='\u8f6e\u64ad\u56fe\u6743\u91cd')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u5546\u54c1\u7c7b\u540d')),
                ('code', models.CharField(default='', max_length=100, verbose_name='\u7c7b\u540d\u7f16\u7801')),
                ('desc', models.TextField(default='', verbose_name='\u7c7b\u522b\u63cf\u8ff0')),
                ('category_type', models.CharField(choices=[('1', '\u4e00\u7ea7\u5206\u7c7b'), ('2', '\u4e8c\u7ea7\u5206\u7c7b'), ('3', '\u4e09\u7ea7\u5206\u7c7b')], max_length=10, verbose_name='\u5206\u7c7b\u7ea7\u522b')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('is_table', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5bfc\u822a\u680f')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_name', to='goods.GoodCategory', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u5206\u7c7b',
                'verbose_name_plural': '\u5546\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('good_sn', models.CharField(default='', max_length=100, verbose_name='\u5546\u54c1\u7f16\u7801')),
                ('desc', models.TextField(default='', verbose_name='\u5546\u54c1\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('click_num', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u70b9\u51fb\u6570')),
                ('sold_num', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u552e\u5356\u6570')),
                ('fav_num', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u5173\u6ce8\u6570')),
                ('goods_num', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u5e93\u5b58\u6570')),
                ('market_price', models.FloatField(default=0.0, verbose_name='\u5e02\u573a\u4ef7\u683c')),
                ('shop_price', models.FloatField(default=0.0, verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('good_desc', DjangoUeditor.models.UEditorField(blank=True, verbose_name='\u5185\u5bb9\t')),
                ('ship_free', models.BooleanField(default=True, verbose_name='\u662f\u5426\u627f\u62c5\u8fd0\u8d39')),
                ('good_front_image', models.ImageField(upload_to='', verbose_name='\u5c01\u9762\u56fe\u7247')),
                ('is_new', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u65b0\u54c1')),
                ('is_hot', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u70ed\u5356\u5546\u54c1')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u54c1\u724c\u540d\u79f0')),
                ('desc', models.TextField(default='', verbose_name='\u54c1\u724c\u63cf\u8ff0')),
                ('images', models.ImageField(max_length=1000, upload_to='brand/images/', verbose_name='\u56fe\u7247')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '\u54c1\u724c',
                'verbose_name_plural': '\u54c1\u724c',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='\u8f6e\u64ad\u56fe')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('index', models.IntegerField(default=100, verbose_name='\u8f6e\u64ad\u56fe\u6743\u91cd')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u5546\u54c1\u8f6e\u64ad\u56fe',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategoryBrand'),
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodCategory', verbose_name='\u5546\u54c1\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods'),
        ),
    ]
