# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 00:22
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180515_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='good_desc',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', max_length=1024000000000L, verbose_name='\u5185\u5bb9'),
        ),
    ]
