# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180515_0022'),
        ('goods', '0002_auto_20180516_1739'),
    ]

    operations = [
    ]
