# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_merge_20180518_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodsimage', to='goods.Goods'),
        ),
    ]
