# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180521_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['index', '-add_time'], 'verbose_name': '\u9996\u9875\u8f6e\u64ad\u56fe', 'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad\u56fe'},
        ),
        migrations.AddField(
            model_name='banner',
            name='desc',
            field=models.CharField(default='', max_length=50, verbose_name='\u63cf\u8ff0\u4fe1\u606f'),
        ),
    ]
