# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-14 22:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='\u5546\u54c1\u6570\u91cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8be6\u7ec6\u4fe1\u606f',
                'verbose_name_plural': '\u8ba2\u5355\u8be6\u7ec6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=100, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='\u7b2c\u4e09\u65b9\u8ba2\u5355\u7f16\u53f7')),
                ('pay_status', models.CharField(choices=[('success', '\u652f\u4ed8\u6210\u529f'), ('cancel', '\u53d6\u6d88\u652f\u4ed8'), ('wait', '\u7b49\u5f85\u652f\u4ed8')], max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('pay_time', models.DateTimeField(verbose_name='\u652f\u4ed8\u65f6\u95f4')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('address', models.CharField(max_length=200, verbose_name='\u5730\u5740')),
                ('signer_name', models.CharField(max_length=50, verbose_name='\u6536\u4ef6\u4eba\u59d3\u540d')),
                ('signer_mobile', models.CharField(max_length=11, verbose_name='\u6536\u4ef6\u4eba\u7535\u8bdd')),
                ('bbs', models.CharField(max_length=50, verbose_name='\u8ba2\u5355\u7559\u8a00')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u4fe1\u606f',
                'verbose_name_plural': '\u8ba2\u5355\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ShoppingTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
    ]
