# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180522_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingtrade',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='shoppingtrade',
            name='goods_num',
            field=models.IntegerField(default=0, verbose_name='\u8d2d\u4e70\u6570\u91cf'),
        ),
    ]
