# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20180522_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '\u8ba2\u5355\u8be6\u60c5', 'verbose_name_plural': '\u8ba2\u5355\u8be6\u60c5'},
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='bbs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8ba2\u5355\u7559\u8a00'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8ba2\u5355\u7f16\u53f7'),
        ),
    ]
