# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180522_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('success', '\u652f\u4ed8\u6210\u529f'), ('cancel', '\u53d6\u6d88\u652f\u4ed8'), ('wait', '\u7b49\u5f85\u652f\u4ed8')], default='wait', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
