# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20180523_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergoods',
            old_name='good_sn',
            new_name='order_sn',
        ),
    ]
