# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20180523_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_time',
            field=models.DateTimeField(verbose_name='\u652f\u4ed8\u65f6\u95f4'),
        ),
    ]
