# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_auto_20180523_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5730\u5740'),
        ),
    ]
