# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-23 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20180523_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='signer_mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='\u6536\u4ef6\u4eba\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='signer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6536\u4ef6\u4eba\u59d3\u540d'),
        ),
    ]
