# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='code_type',
            field=models.CharField(choices=[('0', '\u6ce8\u518c'), ('1', '\u627e\u56de\u5bc6\u7801'), ('2', '\u624b\u673a\u9a8c\u8bc1\u7801\u767b\u5f55')], default='0', max_length=4, verbose_name='\u77ed\u4fe1\u7c7b\u578b'),
        ),
    ]
